id: PDF28083A
initial_creation_type: input
source_metadata:
  Title: ''
  Editor: Pandey, Janardan Shastri
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '2002'
  चक्रसंवरतन्त्रम् [Vol.1]:
    Text Version: Devanagari
    Input Personnel: Milan Shakya
    Input Date: '2013'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of the Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:59:34.147051'
last_modified_at: '2022-03-08T16:59:34.147059'
